CREATE TABLE usuarios (
      id BIGINT AUTO_INCREMENT PRIMARY KEY,
      nome VARCHAR(120) NOT NULL,
      email VARCHAR(160) NOT NULL UNIQUE,
      senha_hash VARCHAR(255) NOT NULL,
      nivel_acesso ENUM('ORGANIZADOR', 'CLIENTE', 'PORTARIA') NOT NULL,
      data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);