server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.open-in-view=false

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}
app.jwt.expiration-hours=${JWT_EXPIRATION_HOURS:24}

server.forward-headers-strategy=framework
